version: 2
updates:
  - package-ecosystem: cargo
    directory: /wolfram
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /boot/uefi
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
